V3 casl 1092 naksha cli versioning (#491)
* feat: add versioning

Signed-off-by: Bartosz Czyż <czyzbartosz3@gmail.com>

* feat: add workflow

Signed-off-by: Bartosz Czyż <czyzbartosz3@gmail.com>

* feat: improved cli script

Signed-off-by: Bartosz Czyż <czyzbartosz3@gmail.com>

---------

Signed-off-by: Bartosz Czyż <czyzbartosz3@gmail.com>

diff --git a/here-naksha-cli/naksha-cli b/here-naksha-cli/naksha-cli
--- a/here-naksha-cli/naksha-cli
+++ b/here-naksha-cli/naksha-cli
@@ -1,13 +1,40 @@
 #!/bin/bash
-set -e # exit on error
+
+# script's args have prefix --S (e.g., --Sbuild)
+args=("$@")
+java_args=()
+script_args=()
+for arg in "${args[@]}"; do
+  if [[ "${arg:0:3}" == "--S" ]]; then
+    script_args+=("$arg")
+  else
+    java_args+=("$arg")
+  fi
+done
+
+rebuild=false
+if [[ " ${script_args[*]} " =~ " --Sbuild " ]]; then
+  rebuild=true
+fi
 
 DIR="$(cd "$(dirname "$0")" && pwd)"
-gradle :here-naksha-cli:jvmJar > /dev/null 2>&1
+version=$(gradle currentVersion | grep "^Project version" | cut -d : -f 2 | xargs)
+JAR="${DIR}/build/libs/naksha-cli-${version}.jar"
 
-JAR=$(find "${DIR}/build/libs" -name "naksha-cli*.jar" -type f -exec ls -t {} + | head -n 1)
+if [[ $rebuild == true ]] || ! [[ -f "$JAR" ]] ; then
+  echo "Building..."
+  stdErr=$(gradle :here-naksha-cli:shadowCreate 2>&1 >/dev/null)
+  gradle_exit=$?
+  if [[ $gradle_exit -ne 0 ]]; then
+    echo "Build failed!" >&2
+    echo $stdErr >&2
+    exit 1
+  fi
+fi
 
 if [[ -f "$JAR" ]]; then
-  java -jar "$JAR" "$@"
+  java -jar "$JAR" "${java_args[@]}"
+  exit $?
 else
   echo "Error: JAR file not found!" >&2
   exit 1
