Disable jacoco tests, because, as we current do not pay, our free limit is reached
Signed-off-by: Alexander Lowey-Weber <alexander.weber@here.com>

diff --git a/.github/workflows/reusable-build-and-publish-v3s.yml b/.github/workflows/reusable-build-and-publish-v3s.yml
--- a/.github/workflows/reusable-build-and-publish-v3s.yml
+++ b/.github/workflows/reusable-build-and-publish-v3s.yml
@@ -55,31 +55,31 @@ jobs:
         shell: bash
         run: |
           gradle cleanAndTest
-      - name: Upload Test Report (HTML)
-        if: success() || failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: jvm-test-report
-          path: '**/build/reports/tests/jvmTest/**/*'
+#      - name: Upload Test Report (HTML)
+#        if: success() || failure()
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: jvm-test-report
+#          path: '**/build/reports/tests/jvmTest/**/*'
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v4
         if: success() || failure() # always run even if the previous step fails
         with:
           report_paths: '**/build/test-results/test/TEST-*.xml'
-      - name: Publish code coverage report as PR comment
-        id: jacoco
-        uses: madrapps/jacoco-report@v1.6.1
-        with:
-          paths: '**/build/reports/jacoco/test/jacocoTestReport.xml'
-          token: ${{ secrets.GITHUB_TOKEN }}
-          min-coverage-overall: $MIN_COVERAGE_OVERALL
-          min-coverage-changed-files: $MIN_COVERAGE_CHANGED_FILES
-          title: Code Coverage
-      - name: Fail when coverage of changed files is too low
-        run: |
-          CHANGED_FILES_FAILED=$(echo '${{ steps.jacoco.outputs.coverage-changed-files }} < ${{ env.MIN_COVERAGE_CHANGED_FILES }}' | bc)
-          [[ $CHANGED_FILES_FAILED -ne 0 ]] && echo 'Changed files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}% is smaller than required ${{ env.MIN_COVERAGE_CHANGED_FILES }}%'
-          [[ $CHANGED_FILES_FAILED -ne 0 ]] && exit 1 || exit 0
+#      - name: Publish code coverage report as PR comment
+#        id: jacoco
+#        uses: madrapps/jacoco-report@v1.6.1
+#        with:
+#          paths: '**/build/reports/jacoco/test/jacocoTestReport.xml'
+#          token: ${{ secrets.GITHUB_TOKEN }}
+#          min-coverage-overall: $MIN_COVERAGE_OVERALL
+#          min-coverage-changed-files: $MIN_COVERAGE_CHANGED_FILES
+#          title: Code Coverage
+#      - name: Fail when coverage of changed files is too low
+#        run: |
+#          CHANGED_FILES_FAILED=$(echo '${{ steps.jacoco.outputs.coverage-changed-files }} < ${{ env.MIN_COVERAGE_CHANGED_FILES }}' | bc)
+#          [[ $CHANGED_FILES_FAILED -ne 0 ]] && echo 'Changed files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}% is smaller than required ${{ env.MIN_COVERAGE_CHANGED_FILES }}%'
+#          [[ $CHANGED_FILES_FAILED -ne 0 ]] && exit 1 || exit 0
 #      - name: List generated artifacts
 #        run: |
 #          ls -l $SERVICE_JAR_DIR/*
